[[command]]
name = "script"
module = "wasmer/winterjs:winterjs"
runner = "wasi"

[command.annotations.wasi]
main-args = [ "--mode", "cloudflare", "/web",]

[package]
name = "syrusakbary/nextjs-starter-4e1"
version = "0.2.1"
description = "Next.js Website (with SSR and API support!) Wasmer starter package"
readme = "README.md"
repository = "https://github.com/syrusakbary/nextjs-starter-4e1"

[dependencies]
"wasmer/winterjs" = "^0.3"

[fs]
"/web" = ".vercel/output/static"
